### PR TITLE
Basic redirects support

### PR DESCRIPTION
**Pull request by laniakea64**
Tested on Firefox and Vivaldi.  This should fix the primary data loss problem.

Redirects support is "WIP" because:

1) I'm not sure what would happen in the following edge case, and I couldn't figure out how to _definitively_ take it into account without breaking other netmon functionality -
```
click link to url1 -> redirects to url2 -> redirects to url3 -> redirects back to url2 (different response but identical url)
```

2) Redirects don't have any special treatment in the UI, they're just shown as separate entries with the redirections in a different color.

Tag https://github.com/kpion/netmon/issues/1#issuecomment-493583911

### CODE REVIEW

**Comment by laniakea64** [comment]
Hi @kpion hope you're doing ok.  Do you need any more info from me to review and merge this?  Thanks

**Comment by kpion** [comment]
Ohhhh, I really thought I already did that... I'm not really experienced with merging requests, seems like I need to select 'merge pull request' and then click 'comment' :) OK, doing this right now....

**Comment by kpion** [comment]
Ah, I had to 'confirm merge', looks like I wasn't focused enough the last time. Sorry for the delay, and thank you very much! I'll soon publish it. Thank you very much again!

**Comment by laniakea64** [comment]
> I'll soon publish it. Thank you very much again!

@kpion you're welcome :slightly_smiling_face: Any news on when this update will be available?

**Comment by kpion** [comment]
I'll try hard in the next 3 days. I did find an issue - the 'archive' doesn't work correctly. I'll get back to in in the next 3 days (or even today, if I'll be able to complete something else).

**Comment by laniakea64** [comment]
Thanks for the update.  What is the issue & what steps to reproduce?

**Pull request merged**
